url: ""
timezone: "America/Sao_Paulo"

collections:
  talks:
    output: true
    permalink: /:title
  speakers:
    output: true
    permalink: /speakers/:title

sass:
  sass_dir: assets/_scss

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
