url: ""
timezone: "America/Sao_Paulo"
lsi: true

collections:
  talks:
    output: true
    permalink: /:title/
  speakers:
    output: true
    permalink: /speakers/:title/
  categories:
    output: true
    permalink: /category/:title/

sass:
  load_paths: 
    - src/scss
    - node_modules

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
