url: "https://devtalks.com.br/"
timezone: "America/Sao_Paulo"

collections:
  - talks

sass:
  sass_dir: assets/_scss

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
